### ISSUE TITLE
Crash on server start.

### ISSUE THREAD

**Issue by darkphan** [codetaylor/ct-watercan#4]
Version: 0.5.5

Crash log: https://pste.me/#/Se45Z

**Comment by codetaylor** [comment]
Built and tested against Forge 1.12.2-14.23.0.2515, no problems.

Updating to Forge 1.12.2-14.23.1.2577.

**Comment by codetaylor** [comment]
Yep, rip server.

```
java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_144]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_144]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_144]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_144]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81) ~[EventBus.class:?]
	at com.sudoplay.mc.ctwatercan.items.watercan.ItemWaterCan.<init>(ItemWaterCan.java:48) ~[ItemWaterCan.class:?]
	at com.sudoplay.mc.ctwatercan.proxy.ProxyCommon.registerItems(ProxyCommon.java:43) ~[ProxyCommon.class:?]
```
